name: LostHunter
author: "LostTeam"
version: 1.1.0
api: [3.0.0]
main: LostTeam\LostHunter
description: "Hunt the entities in your world until their all extinct!"
commands:
  h:
    usage: "/h"
    permission: hunt.cmd
    description: "Hunts All Entities but Players within loaded chunks"
  hunt:
    usage: "/hunt"
    permission: hunt.cmd
    description: "Hunts All Entities but Players within loaded chunks"
permissions:
  hunt.cmd:
    default: op
